name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13E50D7057BA4CA4B1F01C10EFF3F7CC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_297E7E011ADF475388A81F923A8EF425 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF8CD2D68E9941C3822CF3BAFF590204 }}

      - name: Login to Azure Container Registry
        run: az acr login --name gymacrgymapp1085

      - name: Build and Push Docker Image
        run: |
          docker build -t gymacrgymapp1085.azurecr.io/gym-admin:${{ github.sha }} --build-arg NEXT_PUBLIC_API_URL="htttp://localhost:3001/api" .
          docker push gymacrgymapp1085.azurecr.io/gym-admin:${{ github.sha }}
          docker tag gymacrgymapp1085.azurecr.io/gym-admin:${{ github.sha }} gymacrgymapp1085.azurecr.io/gym-admin:latest
          docker push gymacrgymapp1085.azurecr.io/gym-admin:latest

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: gymacrgymapp1085.azurecr.io/gym-admin:${{ github.sha }}
          resourceGroup: gym-aca-rg-gymapp1085
          containerAppName: gym-web-gymapp1085