name: Build and deploy Next.js app to Azure Web App - urbangyms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Zip standalone folder
        run: |
          cd .next/standalone
          zip -r ../../standalone.zip *
          cd ../../

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: standalone-zip
          path: ./standalone.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: standalone-zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13E50D7057BA4CA4B1F01C10EFF3F7CC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_297E7E011ADF475388A81F923A8EF425 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF8CD2D68E9941C3822CF3BAFF590204 }}

      - name: Restart App Service
        uses: azure/webapps-restart@v1
        with:
          app-name: 'urbangyms'
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'urbangyms'
          slot-name: 'Production'
          package: ./standalone.zip
